export const user = [
  {
    fullName: "Igwe Ifeoma Florence",
    email: "flora0841@gmail.com",
    phoneNumber: "08104628806",
    dateOfBirth: "1995-05-12",
    educationQualification: "HND",
    stateOfResidence: "Ekiti",
    LGAOfResidence: " Irepodun/Ifelodun",
    portfolioLink: "",
    programOfChoice: "Graphics Design",
    experienceLevel: "beginner",
    haveLaptop: "No",
    haveInternet: "Yes",
    gender: "female",
    currentAddress: "Behind St. Michael Primary School, Iyin ",
    password: "",
  },
  {
    fullName: "Igwe Ifeoma Florence",
    email: "flora0841@gmail.com",
    phoneNumber: "08104628806",
    dateOfBirth: "1995-05-12",
    educationQualification: "HND",
    stateOfResidence: "Ekiti",
    LGAOfResidence: " Irepodun/Ifelodun",
    portfolioLink: "",
    programOfChoice: "Graphics Design",
    experienceLevel: "beginner",
    haveLaptop: "No",
    haveInternet: "Yes",
    gender: "female",
    currentAddress: "Behind St. Michael Primary School, Iyin ",
    password: "",
  },
  {
    fullName: "Igwe Ifeoma Florence",
    email: "flora0841@gmail.com",
    phoneNumber: "08104628806",
    dateOfBirth: "1995-05-12",
    educationQualification: "HND",
    stateOfResidence: "Ekiti",
    LGAOfResidence: " Irepodun/Ifelodun",
    portfolioLink: "",
    programOfChoice: "Graphics Design",
    experienceLevel: "beginner",
    haveLaptop: "No",
    haveInternet: "Yes",
    gender: "female",
    currentAddress: "Behind St. Michael Primary School, Iyin ",
  },
  {
    fullName: "Igwe Ifeoma Florence",
    email: "flora0841@gmail.com",
    phoneNumber: "08104628806",
    dateOfBirth: "1995-05-12",
    educationQualification: "HND",
    stateOfResidence: "Ekiti",
    LGAOfResidence: " Irepodun/Ifelodun",
    portfolioLink: "",
    programOfChoice: "Graphics Design",
    experienceLevel: "beginner",
    haveLaptop: "No",
    haveInternet: "Yes",
    gender: "female",
    currentAddress: "Behind St. Michael Primary School, Iyin ",
    password: "",
  },
];
